사용자가 검색어를 통해 위치정보를 검색하는 기능을 위한 도메인
f-lab-edu/taxi-service pull request #24
Opened 2024-05-05 09:20 UTC by giwankim

리뷰 부탁드리겠습니다. 🙇 

❓아직 비즈니스 로직이 없고 외부 API와 연결된 port의 리턴값을 그대로 유즈 케이스의 리턴값이라 의미 있는 단위 테스트를 작성했는지 의문입니다. 또 일차 타겟으로 잡은 API에 page,size 파라미터가 있는데 아직 페지네이션에 미숙해서 단순히 keyword로만 검색하게 out-port를 구상했습니다.

💭 다른 한편으로는 이렇게 하나의 in-port의 인자가 다른 out-port의 인자와 구분이 잘 안되거나 비슷한 경우 어뗳게 처리하는 것이 좋을지도 고민됩니다. 이 경우 공통된 인자가 (keyword, page, size)인데 그런 DTO가 여러 패키지에서 사용되는 것은 별로 바람직하지 않다는 생각도 듭니다.

2024-05-06 11:12 UTC, f-lab-scott requested changes
전반적으로 접근 제어자 누락이 너무 많네요. 의도이신가요? 
의도라면 설명해주시면 좋을 것 같긴 한데 모든 필드엔 적절한 수준의 접근 제어를 부여하는 것을 원칙으로 해 주시면 좋을 것 같습니다. 🙇

2024-05-06 11:12 UTC, f-lab-scott commented on core/core-domain/src/main/java/com/giwankim/taxiservice/core/domain/application/port/in/SearchLocationsQuery.java
> +  Integer size;
적절한 접근 제어자가 부여되어야 할 것 같습니다.

2024-05-06 11:12 UTC, f-lab-scott commented on core/core-domain/src/main/java/com/giwankim/taxiservice/core/domain/application/port/in/SearchLocationsQuery.java
> +    this.validateSelf();
이 부분은 Spring MVC에 위임하면 좋을 것 같고, domain layer로 진입하는 port들에 대해서는 생략해도 된다는 생각입니다.

2024-05-06 11:12 UTC, f-lab-scott commented on core/core-domain/src/test/java/com/giwankim/taxiservice/core/domain/application/port/in/SearchLocationsQueryTest.java
> +class SearchLocationsQueryTest {
지금 단계에선 이런 정도의 단위 테스트라도 의미가 없는 것이 아닙니다.
다만 도메인이 복잡해지고 점점 구현이 고도화되면서 이 테스트의 내용도 충실해져야 할 것 같습니다.

2024-05-08 08:53 UTC, giwankim commented on core/core-domain/src/main/java/com/giwankim/taxiservice/core/domain/application/port/in/SearchLocationsQuery.java
> +  Integer size;
롬복 Value 어노테이션을 사용하니까 IDE에서 package-private은 자동으로 private로 변환된다고 노란줄이 띄워져서 제어자를 제거했습니다.

클래스들을 더 일반적인 자바 클래스로 변경했습니다. `SearchLocationsQuery`는 불변객체라 record로 변환했고 `Location` 객체에 @Value를 사용했던 이유는 value object처럼 id 없이 사용되지 않을까 헤서였는데 가독성이 떨어졌던 것 같습니다.

2024-05-08 09:00 UTC, giwankim commented on core/core-domain/src/main/java/com/giwankim/taxiservice/core/domain/application/port/in/SearchLocationsQuery.java
> +    this.validateSelf();
발리테이션 제거했습니다. 그러면서 Integer 였던 속성도 int로 바꿨습니다. 이 경우 Integer를 사용한 이유는 null일 수 있도록 허용하자는 의도였는데 클래스 속성에 wrapper class를 사용할지 판단 기준에 어떤 것들이 있을까요?

2024-05-10 08:40 UTC, f-lab-scott commented on core/core-domain/src/main/java/com/giwankim/taxiservice/core/domain/application/port/in/SearchLocationsQuery.java
> +    this.validateSelf();
@giwankim 개인적인 관점에선 autoboxing/unboxing이 얼마나 자주 일어나느냐에 대해서 판단해보는 편입니다. 자주 일어나는 쪽이라면 사용하지 않는 것이 여러모로 유리합니다. 그리고 말씀처럼 `null` 을 사용할 것인가... 에 대한 관점도 매우 유효합니다.

2024-05-10 08:41 UTC, f-lab-scott approved these changes

2024-05-11 00:55 UTC, merged