키워드로 위치 정보를 조회하기 위한 web adapter 구현
f-lab-edu/taxi-service pull request #28
Opened 2024-05-12 04:33 UTC by giwankim

- 웹 어댑터 구현
- H2로 로컬 개발 데이터베이스 교체
- revert 되었던 enum 모듈을 다시 추가

2024-05-12 10:05 UTC, f-lab-scott requested changes
마지막으로 몇 가지만 더 챙겨보시면 좋겠습니다

2024-05-12 10:05 UTC, f-lab-scott commented on core/core-api/src/main/java/com/giwankim/taxiservice/core/api/controller/ApiControllerAdvice.java
> +      default -> logger.info("CoreApiException : {}", e.getMessage(), e);
이거 요렇게 처리하면 살짝 위험성이 있긴 합니다(중요한 건은 아닙니다).
`logging.level.root` 설정에 따라 로깅이 의도대로 되지 않을 확률이 있습니다. 특히 default case가 info 레벨인 것이 조금 걸리는데, 더 나은 방법이 없을까요?

2024-05-12 10:05 UTC, f-lab-scott commented on core/core-api/src/main/java/com/giwankim/taxiservice/core/api/controller/ApiControllerAdvice.java
> +  public ResponseEntity<ApiResponse<?>> handleCoreApiException(CoreApiException e) {
와일드카드 제너릭으로 처리하기보단, 어차피 `Exception` 만 처리해야 하는 응답 포맷이므로,
예외 케이스 용 응답 클래스가 하나 있으면 좋을 거 같네요.

2024-05-12 10:05 UTC, f-lab-scott commented on core/core-api/src/main/java/com/giwankim/taxiservice/core/api/controller/HealthController.java
> +  @GetMapping("/health")
[Spring Actuator](https://incheol-jung.gitbook.io/docs/study/srping-in-action-5th/chap-16.) 같이 공부해보시면 좋겠네요

2024-05-19 08:25 UTC, giwankim commented on core/core-api/src/main/java/com/giwankim/taxiservice/core/api/controller/ApiControllerAdvice.java
> +      default -> logger.info("CoreApiException : {}", e.getMessage(), e);
이 부분은 혹시 `logging.level.root`가 INFO 보다 높게 설정되어 있으면 로그가 안 찍힐 수 있어서 그런 것인가요?

2024-05-31 00:16 UTC, f-lab-scott approved these changes

2024-06-02 05:17 UTC, merged