카카오 API를 사용한 geocoding 클라이언트 추가
f-lab-edu/taxi-service pull request #29
Opened 2024-05-19 08:33 UTC by giwankim

Geocoding 정보를 조회하는 client를 추가했습니다.

2024-05-24 14:17 UTC, f-lab-scott requested changes
여러가지 골치아픈 일이 있었어서 리뷰가 너무 늦어졌네요; 다음부턴 재촉도 해주시면 감사하겠습니다;
너무 늦은 리뷰에 죄송하고, 간단하게 손대면 되는 것 다섯개 정도, 좀 고민해보셔야 하는 것 세가지 정도 있습니다. 확인 부탁드립니다 🙇

2024-05-24 14:17 UTC, f-lab-scott commented on clients/location-client/src/main/java/com/giwankim/taxiservice/client/location/kakao/KakaoLocationClient.java
> +  }
요런건 간단하게 롬복으로 대체해 보세요.

2024-05-24 14:17 UTC, f-lab-scott commented on clients/location-client/src/main/java/com/giwankim/taxiservice/client/location/kakao/KakaoLocationClient.java
> +  public List<Location> searchLocations(String keyword, int page, int size) {
`keyword`, `page`, `size` 를 맵핑해둔 command나 request 인터페이스는 작성하지 않는 방향으로 의사결정 하신걸까요?

2024-05-24 14:17 UTC, f-lab-scott commented on clients/location-client/src/main/java/com/giwankim/taxiservice/client/location/kakao/KakaoLocationMapper.java
> +  List<Location> mapToLocations(KakaoLocationResponse response) {
`response.document` 단건을 파라메터로 받는 스태틱 팩토리 메서드가 `Location` 쪽에 작성되어 있으면 이 컴포넌트는 필요없지 않을까요?

이게 빈으로 관리되어야 하는 로직인지는 저는 잘 모르겠습니다.

2024-05-24 14:17 UTC, f-lab-scott commented on clients/location-client/src/test/java/com/giwankim/taxiservice/client/location/kakao/KakaoLocationClientTest.java
> +        .withStatus(HttpStatus.OK.value())));
스터빙 굳입니다 👍

2024-05-24 14:17 UTC, f-lab-scott commented on core/core-api/src/main/java/com/giwankim/taxiservice/core/api/controller/ApiControllerAdvice.java
> +      default -> logger.info("CoreApiException : {}", e.getMessage(), e);
로그 레벨별 출력 메세지가 모두 같은데요, 이렇게 패턴 매칭으로 분기를 해버리면... 로그 레벨을 부여하는 이유가 흐려지지 않을까요?
`ERROR` 로 놓건 `WARN` 으로 놓건 메세지는 다 표시되겠네요. 그만큼 중요한 에러여서일까요. 그렇게 보이진 않습니다.
Spring이나 hibernate같은 잘 알려진 라이브러리에서 요런 패턴이 자주 보이긴 하는데, 그거는 애플리케이션의 구동 성공/실패를 가르는 중요한 메세지들이어서 그런 거고요, 사용자의 입력으로도 유발될 수 있는 애매한 익셉션을 요렇게 처리하는 것은 베스트 프랙티스는 아닐 거 같습니다.

2024-05-24 14:17 UTC, f-lab-scott commented on core/core-api/src/main/java/com/giwankim/taxiservice/core/api/controller/HealthController.java
> +  @GetMapping("/health")
Spring Actuator로 대체할 수 있습니다 찾아보시죠

2024-05-24 14:17 UTC, f-lab-scott commented on core/core-api/src/main/java/com/giwankim/taxiservice/core/api/support/error/ErrorCode.java
> +public enum ErrorCode {
`ErrorCode` 에서 메세지도 같이 관리되는 편이 좋긴 합니다

2024-05-24 14:17 UTC, f-lab-scott commented on core/core-api/src/main/java/com/giwankim/taxiservice/core/api/support/error/ErrorType.java
> +  private final ErrorCode code;
`ErrorCode` 가 `ErrorType` 을 갖고 있는 형태가 좀 더 자연스러워 보이긴 합니다만...

2024-05-26 01:12 UTC, giwankim commented on clients/location-client/src/main/java/com/giwankim/taxiservice/client/location/kakao/KakaoLocationClient.java
> +  public List<Location> searchLocations(String keyword, int page, int size) {
Spring Data JPA 기능들 인강으로 공부 중인데 다음 파트입니다. 웹과 연동되는 점들을 생각하면 Pageable과 리턴 타입의 Slice 인터페이스를 사용하는 것이 좋을 것 같습니다.

2024-05-26 01:26 UTC, giwankim commented on core/core-api/src/main/java/com/giwankim/taxiservice/core/api/controller/HealthController.java
> +  @GetMapping("/health")
https://github.com/f-lab-edu/taxi-service/pull/28 PR에 반영되어 있습니다.

2024-05-26 02:51 UTC, giwankim commented on core/core-api/src/main/java/com/giwankim/taxiservice/core/api/controller/ApiControllerAdvice.java
> +      default -> logger.info("CoreApiException : {}", e.getMessage(), e);
생각해보니 API 예외의 주된 역할이 에러 코드나 메시지를 통해서 API 사용자들에게 왜 요청이 실패했는지 전달하는 것이다 보니 사실상 로그를 남기는 것이 그리 중요하지는 않다고 판단됩니다. 다만 예상치 못한 예외 같은 경우 error 레벨로 로그를 남겨서 시간당 어느 수준 이상 발생하면 슬랙 알람을 남길 수 있는 구조가 좋을 것 같습니다.
 
그럼 API 예외 클래스에 로그 레벨 속성이 의마가 있는 것일까요? Global exception handler에서는 혹시나 모르니 그냥 일관되게 debug 레벨의 로그를 찍는 것도 어떨지라는 생각이 듭니다. 이런 전략에 대해서는 어떻게 생각하시는지요?

2024-05-27 04:12 UTC, giwankim commented on clients/location-client/src/main/java/com/giwankim/taxiservice/client/location/kakao/KakaoLocationClient.java
> +  public List<Location> searchLocations(String keyword, int page, int size) {
페이징 관련 Spring Data JPA를 사용할지 도메인 모듈에 비슷하게 구현할지 고민됩니다. 보니까 다 좋은데 외부 API에서는 page가 1부터 시작하는 반면에 JPA repository는 페이지가 0부터 시작하는군요.

2024-05-27 06:11 UTC, giwankim commented on clients/location-client/src/main/java/com/giwankim/taxiservice/client/location/kakao/KakaoLocationClient.java
> +  public List<Location> searchLocations(String keyword, int page, int size) {
그리고 controller에서 Pageable 인터페이스로 받은 인자를 발리데이션 하기 위해서 조금 더 작업이 필요한 것 같습니다.  제가 찾아본 방법으로는 ConstraintValidator 인터페이스를 구현하고 @Constraint(validatedBy=Validator.class) 어노테이션을 달고 있는 어노테이션을 추가 구현하고 하는 방법인데 조금 복잡해지는 감이 있습니다.

2024-05-31 00:16 UTC, f-lab-scott approved these changes

2024-06-02 05:17 UTC, merged