기본 요금 정보 조회를 위한 외부 API 클라이언트 추가
f-lab-edu/taxi-service pull request #30
Opened 2024-06-06 02:41 UTC by giwankim

린터를 동작시켜서 실제 추가된 파일 수보다 변화된 파일이 많게 잡히고 있습니다. 이점 양해 부탁드립니다. 🙇 

- 기본 요금 조회하는 클라이언트
- 도메인에 Money와 Ratio 클래스 추가

2024-06-08 05:30 UTC, f-lab-scott requested changes
몇 가지 의견 드립니다.

2024-06-08 05:30 UTC, f-lab-scott commented on clients/fare-client/src/main/java/com/giwankim/taxiservice/client/fare/kakao/KakaoFareConfig.java
> +  @Value("${fare.kakao.api.key}")
`fare.kakao` 로 시작하는 configuration properties가 좀 있는 듯한데, 하나의 클래스로 관리하는 방법 고민해 주세요.
https://www.baeldung.com/configuration-properties-in-spring-boot

2024-06-08 05:30 UTC, f-lab-scott commented on clients/fare-client/src/main/java/com/giwankim/taxiservice/client/fare/kakao/KakaoFareConfig.java
> +  RequestInterceptor requestInterceptor() {
`public` 접근 제어자 달아주시고요

2024-06-08 05:30 UTC, f-lab-scott commented on clients/fare-client/src/test/java/com/giwankim/taxiservice/client/fare/kakao/KakaoFareClientTest.java
> +            .withQueryParam("destination", matching("^(-?\\d+(\\.\\d+)?),(-?\\d+(\\.\\d+)?)$"))
테스트 단계니까 사실 어떤 요청이든 매치되어도 상관없지 않나요?

2024-06-08 05:30 UTC, f-lab-scott commented on core/core-domain/src/main/java/com/giwankim/taxiservice/core/domain/domain/Money.java
> +  public String toString() {
`.toString()` 의 이런 변형은 삼가시는 것이 좋습니다.
`.toString()` 은 정말 객체의 상태 표현 그 자체에 집중하는 것이 좋고 디스플레이용 문자열이 필요하다면 별도의 메소드를 구현하는 것을 추천 드립니다.

2024-06-08 05:30 UTC, f-lab-scott commented on core/core-domain/src/main/java/com/giwankim/taxiservice/core/domain/domain/Money.java
> +  }
이런 연산이 필요한 오브젝트들에 대한 일반화된 프로토콜이 필요하지 않을지도 고민해 보시면 좋겠네요.
그러니까 이런 연산이 정의되는 별도의 인터페이스가 필요하진 않을까? 를 고민해 보시면 됩니다

2024-06-09 07:22 UTC, giwankim commented on core/core-domain/src/main/java/com/giwankim/taxiservice/core/domain/domain/Money.java
> +  }
추가적으로 이런 클래스는 실무에서는 직접 구현하기보다는 라이브러리를 사용할 것도 같다는 생각이 들었습니다.
- https://www.baeldung.com/java-money-and-currency
- https://www.joda.org/joda-money/
와 같은 라이브러리들이 있는 것 같았지만 원화만 지원하는 비교적 간단한 유즈케이스라는 생각이 들어서 그냥 구현체를 추가했습니다.

사칙연산 인터페이스를 추가하기에 약간 애매한 감도 있는 것 같습니다. 다시 재사용할지 의문이 들고 `times(double percent)`와 같은 메서드가 있는데 사칙연산 인터페이스에서는  `<T> times(T other)` 가 있어야 할 것 같습니다.

2024-06-15 23:09 UTC, f-lab-scott approved these changes

2024-06-15 23:11 UTC, f-lab-scott commented on core/core-domain/src/main/java/com/giwankim/taxiservice/core/domain/domain/Money.java
> +  }
@giwankim 잘 알려진 라이브러리를 사용하시는 것도 좋은 방법입니다.

2024-06-16 03:33 UTC, merged