길찾기 API 연동 구현
f-lab-edu/taxi-service pull request #31
Opened 2024-06-06 04:21 UTC by giwankim

시간상 길 찾기 상세 정보는 추가하지 않았습니다.

2024-06-08 05:49 UTC, f-lab-scott requested changes
PR마다 내용이 좀 중복되는 부분이 발생하는 것 같은데;; 혹시 어떤 이유일까요?
그리고 `File` 쪽 내용은 자세히 봐주시길 부탁드립니다.

2024-06-08 05:49 UTC, f-lab-scott commented on clients/directions-client/src/main/java/com/giwankim/taxiservice/client/directions/kakao/KakaoDirectionsConfig.java
> +  private String apiUrl;
요것도 config properties로 묶어주세요~

2024-06-08 05:49 UTC, f-lab-scott commented on clients/directions-client/src/test/java/com/giwankim/taxiservice/client/directions/FileUtils.java
> +      return new String(Files.readAllBytes(file.toPath()));
`new String()` 을 호출하는 것의 위험성에 대해서도 한번 학습해보시면 좋겠고요.
기본적으로 텍스트 파일의 경우엔 한 줄씩 읽어들이는 것이 안전해 보이는데요, 이 메소드는 여러모로 위험성이 커 보입니다.
혹시 한 줄씩 읽어들이는 방향으로의 개선은 어려울까요?

2024-06-09 07:14 UTC, giwankim commented on clients/directions-client/src/test/java/com/giwankim/taxiservice/client/directions/FileUtils.java
> +      return new String(Files.readAllBytes(file.toPath()));
혹시 string interning 때문에 `new String()` 호출을 지양해야 한다고 하시는 것일까요?

2024-06-15 23:10 UTC, f-lab-scott commented on clients/directions-client/src/test/java/com/giwankim/taxiservice/client/directions/FileUtils.java
> +      return new String(Files.readAllBytes(file.toPath()));
@giwankim 네 맞습니다.

2024-06-15 23:10 UTC, f-lab-scott approved these changes

2024-06-16 03:38 UTC, merged